artifact_location: file:///F:/My File/MERNxAI/ML-DL Work/blood-image-nfsw/gun-Ops/runs/mlflow/342147219522647898
creation_time: 1743943511242
experiment_id: '342147219522647898'
last_update_time: 1743943511242
lifecycle_stage: active
name: /Shared/Ultralytics
