artifact_location: file:///F:/My File/MERNxAI/ML-DL Work/blood-image-nfsw/gun-Ops/runs/mlflow/0
creation_time: 1743943511061
experiment_id: '0'
last_update_time: 1743943511061
lifecycle_stage: active
name: Default
